on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Turbo
        run: pnpm install -g turbo
      - name: Typecheck
        run: turbo check-types
      - name: Lint
        run: turbo lint
